### ISSUE TITLE
why is sample using 'heinz.org' in a config 

### ISSUE THREAD

**Issue by mgevantmakher** [SolaceLabs/pubsubplus-connector-kafka-sink#14]
https://github.com/SolaceLabs/pubsubplus-connector-kafka-sink/blob/master/krb5.conf

**Comment by hschaffner** [comment]
This is just a sample configuration. The "heinz.org" is just an artifact from when I added Kerberos to the connector since I created my own DNS and Kerberos environment for testing

**Comment by mgevantmakher** [comment]
heinz.org domain exists and it is not related to solace...

**Comment by hschaffner** [comment]
Correct, but I created this for internal testing using my own DNS server and Kerberos setup. Since my name is “Heinz” I just picked heinz.org for testing Kerberos with the connector. There is no relation between Solace and heinz.org.

Heinz Schaffner



[photo]
Heinz Schaffner B.Sc., MBA
Principal Technologist, Office of the CTO
Solace.com<https://solace.com/> | +1 416-301-5488 | heinz.schaffner@solace.com<mailto:heinz.schaffner@solace.com>

**Comment by mgevantmakher** [comment]
it is public repo isn't it?

**Comment by mgevantmakher** [comment]
Philippe asked me to create a bug report after I found it because it is public repo.

**Comment by hschaffner** [comment]
No problem, if you want to change it is no problem, however, there are a couple of files with “heinz.org”, so you would need to make sure you change them all to be consistent!

Heinz
